name: "Multi-Blog Publisher"
description: "Publish markdown blog post to Dev.to, Medium, and Hashnode"
inputs:
  markdown_file:
    description: "Path to markdown file"
    required: true
  devto_api_key:
    description: "Dev.to API key"
    required: true
  medium_token:
    description: "Medium integration token"
    required: true
  hashnode_api_key:
    description: "Hashnode API token"
    required: true
  # cookies_file:
  #   description: "Path to Medium cookies.txt"
  #   required: true
runs:
  using: 'node20'
  main: 'dist/index.js'

